spring:
  datasource:
    username: root
    password: YANGyajie2004
    url: jdbc:mysql://localhost/mysqldemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  driver-class-name: com.mysql.cj.jdbc.Driver
